Practical Questions Assignment

In [ ]:
#21
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("gpt2")
text = "Large Language Models are transforming the world."
tokens = tokenizer.tokenize(text)
token_ids = tokenizer.convert_tokens_to_ids(tokens)

print("Tokens:")
print(tokens)
print("\nToken IDs:")
print(token_ids)

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Tokens:
['Large', 'ĠLanguage', 'ĠModels', 'Ġare', 'Ġtransforming', 'Ġthe', 'Ġworld', '.']

Token IDs:
[21968, 15417, 32329, 389, 25449, 262, 995, 13]


In [ ]:
#22
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("gpt2")
words = ["unbelievable", "cat"]

for word in words:
    print(word)
    print(tokenizer.tokenize(word))
    print()

unbelievable
['un', 'bel', 'iev', 'able']

cat
['cat']



In [ ]:
#23
from transformers import pipeline
generator = pipeline("text-generation", model="gpt2")
prompt = "Artificial Intelligence is"

output1 = generator(prompt, max_new_tokens=50)
output2 = generator(prompt, max_new_tokens=50)

print("First Output:\n")
print(output1[0]["generated_text"])
print("\nSecond Output:\n")
print(output2[0]["generated_text"])

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

[transformers] Passing `generation_config` together with generation-related arguments=({'max_new_tokens'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Both `max_new_tokens` (=50) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer GPT2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=T

First Output:

Artificial Intelligence is a key element of the problem, and for that reason the question is whether a real social network can be trained to follow this pattern.

The answer is that there's a lot of work to be done.

But I'm not interested

Second Output:

Artificial Intelligence is an attempt to develop a fully distributed system, one that is not based on the same hardware or software as the hardware or software used to control our vehicles. Our vision is to build a system with the capabilities of AI, allowing it to interact with the


In [ ]:
#24
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
sentences = [
    "I like AI",
    "Transformers are powerful models",
    "Machine Learning"
]

encoded = tokenizer(
    sentences,
    padding=True,
    return_tensors="pt"
)
print("Input IDs")
print(encoded["input_ids"])
print("\nAttention Mask")
print(encoded["attention_mask"])

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Input IDs
tensor([[  101,  1045,  2066,  9932,   102,     0],
        [  101, 19081,  2024,  3928,  4275,   102],
        [  101,  3698,  4083,   102,     0,     0]])

Attention Mask
tensor([[1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 0, 0]])


In [ ]:
#25
from transformers import AutoTokenizer, AutoModel
import torch

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
model = AutoModel.from_pretrained("bert-base-uncased")

sentences = [
    "I deposited money in the bank.",
    "The children played near the bank of the river."
]

for sentence in sentences:
    inputs = tokenizer(sentence, return_tensors="pt")
    with torch.no_grad():
        outputs = model(**inputs)

    index = inputs.tokens().index("bank")
    embedding = outputs.last_hidden_state[0, index]

    print(sentence)
    print(embedding[:10])
    print()

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  | 
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.weight     | UNEXPECTED |  | 
cls.seq_relationship.weight                | UNEXPECTED |  | 
cls.predictions.transform.dense.bias       | UNEXPECTED |  | 
cls.predictions.bias                       | UNEXPECTED |  | 
cls.seq_relationship.bias                  | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.


I deposited money in the bank.
tensor([ 0.5343, -0.3769, -0.1306,  0.1728,  0.9833,  0.1560, -0.7062,  0.8090,
        -0.1534, -0.0731])

The children played near the bank of the river.
tensor([-0.3633, -0.3119, -0.0529,  0.1302,  0.0334,  0.3345,  0.1835,  1.6157,
        -0.0822, -0.4888])



In [ ]:
#26
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
model = SentenceTransformer("all-MiniLM-L6-v2")
sentences = [
    "Artificial Intelligence",
    "Machine Learning",
    "I love pizza"
]
embeddings = model.encode(sentences)
similarity = cosine_similarity(embeddings)
print(similarity)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

[[1.0000001  0.7034625  0.1269484 ]
 [0.7034625  1.0000001  0.08875057]
 [0.1269484  0.08875057 1.0000001 ]]


In [ ]:
#27
import torch
import math

X = torch.rand(3, 4)
Q = X
K = X
V = X

scores = torch.matmul(Q, K.T)
scores = scores / math.sqrt(Q.shape[1])
weights = torch.softmax(scores, dim=-1)
context = torch.matmul(weights, V)

print("Attention Weights")
print(weights)
print("\nContext Vector")
print(context)

Attention Weights
tensor([[0.3772, 0.3239, 0.2989],
        [0.3192, 0.3901, 0.2907],
        [0.3288, 0.3245, 0.3467]])

Context Vector
tensor([[0.4002, 0.4568, 0.6180, 0.4115],
        [0.3799, 0.5032, 0.6096, 0.3976],
        [0.4134, 0.4701, 0.5873, 0.4063]])


In [ ]:
#28
import torch

x = torch.rand(2, 5, 32)
heads = 4
head_dim = 32 // heads

x = x.view(2, 5, heads, head_dim)
x = x.permute(0, 2, 1, 3)

out = x.permute(0, 2, 1, 3).contiguous().view(2, 5, 32)
linear = torch.nn.Linear(32, 32)
final_output = linear(out)
print(out.shape)
print(final_output.shape)

torch.Size([2, 5, 32])
torch.Size([2, 5, 32])


In [ ]:
#29
import torch
scores = torch.rand(5, 5)
mask = torch.triu(torch.ones(5, 5), diagonal=1)
scores = scores.masked_fill(mask == 1, float("-inf"))
attention = torch.softmax(scores, dim=-1)

print("Masked Scores")
print(scores)
print("\nAfter Softmax")
print(attention)

Masked Scores
tensor([[0.8112,   -inf,   -inf,   -inf,   -inf],
        [0.7845, 0.3838,   -inf,   -inf,   -inf],
        [0.1817, 0.4904, 0.9387,   -inf,   -inf],
        [0.5010, 0.5547, 0.3005, 0.9591,   -inf],
        [0.6298, 0.3974, 0.5751, 0.6887, 0.8242]])

After Softmax
tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5989, 0.4011, 0.0000, 0.0000, 0.0000],
        [0.2225, 0.3030, 0.4744, 0.0000, 0.0000],
        [0.2245, 0.2369, 0.1837, 0.3549, 0.0000],
        [0.1994, 0.1581, 0.1888, 0.2115, 0.2422]])


In [ ]:
#30
import torch
import torch.nn as nn

class DecoderBlock(nn.Module):
    def __init__(self):
        super().__init__()
        self.attention = nn.MultiheadAttention(32, 4, batch_first=True)
        self.norm1 = nn.LayerNorm(32)
        self.ffn = nn.Sequential(
            nn.Linear(32, 64),
            nn.ReLU(),
            nn.Linear(64, 32)
        )
        self.norm2 = nn.LayerNorm(32)

    def forward(self, x):
        attn, _ = self.attention(x, x, x)
        x = self.norm1(x + attn)
        ffn = self.ffn(x)
        x = self.norm2(x + ffn)
        return x

model = DecoderBlock()
x = torch.rand(2, 5, 32)
output = model(x)
print(output.shape)

torch.Size([2, 5, 32])
